version: "3"

services:
  api-tests:
    image: postman/newman:latest
    volumes:
      - ./api-tests/postman:/etc/newman
    working_dir: /etc/newman
    command: >
      run posts-crud-collection.json
      --reporters cli,json
      --reporter-json-export newman-report.json

  performance-jmeter:
    image: justb4/jmeter
    container_name: jmeter-tests
    volumes:
      - ./performance-tests/jmeter:/test
    command: -n -t /test/posts-crud.jmx -l /test/results.jtl

  ui-tests:
    build:
      context: ./ui-tests
      dockerfile: Dockerfile
    container_name: ui-tests
    volumes:
      - ./ui-tests:/app
    working_dir: /app
    command: ["npx", "playwright", "test"]

